// <auto-generated />
using Banico.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Banico.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Banico.Core.Entities.ContentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alias");

                    b.Property<string>("Attribute01");

                    b.Property<string>("Attribute02");

                    b.Property<string>("Attribute03");

                    b.Property<string>("Attribute04");

                    b.Property<string>("Attribute05");

                    b.Property<string>("Attribute06");

                    b.Property<string>("Attribute07");

                    b.Property<string>("Attribute08");

                    b.Property<string>("Attribute09");

                    b.Property<string>("Attribute10");

                    b.Property<string>("Attribute11");

                    b.Property<string>("Attribute12");

                    b.Property<string>("Attribute13");

                    b.Property<string>("Attribute14");

                    b.Property<string>("Attribute15");

                    b.Property<string>("Attribute16");

                    b.Property<string>("Attribute17");

                    b.Property<string>("Attribute18");

                    b.Property<string>("Attribute19");

                    b.Property<string>("Attribute20");

                    b.Property<string>("Content");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<DateTimeOffset>("LastUpdate");

                    b.Property<string>("Name");

                    b.Property<int>("ParentId");

                    b.Property<string>("Sections");

                    b.Property<string>("Tenant");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("ContentItems");
                });

            modelBuilder.Entity("Banico.Core.Entities.Invite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Email");

                    b.Property<string>("Inviter");

                    b.HasKey("Id");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("Banico.Core.Entities.SectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alias");

                    b.Property<string>("Breadcrumb");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<DateTimeOffset>("LastUpdate");

                    b.Property<string>("Name");

                    b.Property<int>("ParentId");

                    b.Property<string>("Path");

                    b.Property<string>("Tenant");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("SectionItems");
                });

            modelBuilder.Entity("Banico.Core.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<DateTimeOffset>("LastUpdate");

                    b.Property<string>("Modules");

                    b.Property<string>("Name");

                    b.Property<string>("Tenant");

                    b.HasKey("Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Banico.Core.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EntryTime");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
